FROM ubuntu:latest

# Update the list of packages
RUN apt-get update

# Install pre-requisite packages.
RUN apt-get install -y wget apt-transport-https software-properties-common

# Download the Microsoft repository GPG keys
RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
RUN dpkg -i packages-microsoft-prod.deb

# Update the list of products
RUN apt-get update

# Enable the "universe" repositories
RUN add-apt-repository universe

# Install PowerShell
RUN apt-get install -y powershell

# Install Git
RUN apt-get install git -y

#Create User
RUN useradd -ms /bin/bash researcher
USER researcher
WORKDIR /home/researcher


# Clone Repo
RUN git clone https://github.com/NetSPI/MicroBurst.git

#Change into Repo Directory
WORKDIR /home/researcher/MicroBurst

#Create Persistence Profle
RUN mkdir -p /home/researcher/.config/powershell/
RUN echo "Install-Module -Name Az -Repository PSGallery -PassThru" > /home/researcher/.config/powershell/Microsoft.PowerShell_profile.ps1
RUN echo "Install-Module -Name AzureAD -PassThru" > /home/researcher/.config/powershell/Microsoft.PowerShell_profile.ps1
RUN echo "Install-Module -Name MSOnline -PassThru" > /home/researcher/.config/powershell/Microsoft.PowerShell_profile.ps1
RUN echo "Import-Module ./MicroBurst.psm1 -PassThru" > /home/researcher/.config/powershell/Microsoft.PowerShell_profile.ps1

#Install Modules
SHELL ["pwsh", "Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force"]
SHELL ["pwsh", "Install-Module -Name AzureAD -Force"]
SHELL ["pwsh", "Install-Module -Name MSOnline -Force"]
SHELL ["pwsh", "Import-Module ./MicroBurst.psm1 -Force"]

ENTRYPOINT ["pwsh"]
