FROM ubuntu:latest
FROM ubuntu:latest

RUN apt-get update

RUN apt install python3-pip -y

RUN apt-get install git -y 
RUN useradd -ms /bin/bash researcher
USER researcher
WORKDIR /home/researcher

RUN git clone https://github.com/initstring/cloud_enum.git

WORKDIR /home/researcher/cloud_enum

RUN pip3 install -r ./requirements.txt

ENTRYPOINT ["python3", "cloud_enum.py", "-k"]
